### ISSUE TITLE
Create default dashboards

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ui#102]
This issue is about bringing all the charts from the PoCs and demos that don't require any pre-preprocessing, and can be run with the current data provided by sourced-ce.

**Comment by smacker** [comment]
list of charts in demo that use only gitbase:
- Repository Count
- Languages
- Commits Evolution
- Repositories by number of files
- Number of commits per day of the week (all projects)
- Compliance score
- Missing files
- Files missing summary
