### ISSUE TITLE
Replace ttf fonts with web fonts

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#108]
https://github.com/src-d/sourced-ui/pull/106 introduced new fonts but they aren't optimized for web. We will need to improve it by using some more suitable format. For example woff2.

**Comment by marnovo** [comment]
@smacker @ricardobaeta indeed, we have the web fonts available for our typefaces at our [root > Product > Design > Brand Guidelines > Typefaces drive folders](https://drive.google.com/drive/u/0/folders/1r0t1FmnnYH2erwWTB3CFZ9IpxZ04vFQV)

**Comment by ricardobaeta** [comment]
@smacker @marnovo [This commit](https://github.com/src-d/sourced-ui/pull/106/commits/289dc6756059c20a00333128debbe64dd97ff2e6) on the [source{d} branded superset UI PR](https://github.com/src-d/sourced-ui/pull/106) solves this issue.
