### ISSUE TITLE
Tables overflow the chart container

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#114]
<img width="474" alt="Screenshot 2019-06-17 at 12 22 20" src="https://user-images.githubusercontent.com/406916/59597653-9ce52f00-90fa-11e9-81cd-24707754ad9a.png">

I thought it would be possible to fix with making the container bigger but it fixes the issue only when the table is small. For a table with many elements changing size of the chart doesn't help.

**Comment by marnovo** [comment]
@smacker @ricardobaeta isn't this caused (or fixed) by some layout or overflow property?

**Comment by smacker** [comment]
most probably it's possible to fix by overflow property but it may break some other things.
Anyway, I didn't have time to dig deep into it and trust Ricardo for a proper fix.

**Comment by ricardobaeta** [comment]
@marnovo This is caused by a margin-bottom attributed to the Chart Title, on the Typography PR. I will check with @dpordomingo this and tackle the issue.

**Comment by marnovo** [comment]
@ricardobaeta please make sure to test this broadly with the built-in and new charts of varied types/sizes.

**Comment by ricardobaeta** [comment]
@marnovo I've tested the built-in charts, and it's all fine. The only built-in chart that is not good is the "Welcome" > "Files missing summary" that's [issued here](https://github.com/src-d/sourced-ui/issues/118). We can make it look good when we're updating this dashboard with the welcome text and the progress bars, changing its height on "Edit Dashboard" before we update it.

The new charts of varied types/sizes were tested, and it's all good as well, given that the [solution](https://github.com/src-d/sourced-ui/issues/114#issuecomment-503976803) applies also to all new charts, and moreover we can control the width & height of new charts when we're creating/editing a new dashboard.
