### ISSUE TITLE
Incorrect chart for releases

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#115]
<img width="1410" alt="Screenshot 2019-06-17 at 12 24 06" src="https://user-images.githubusercontent.com/406916/59597729-d5850880-90fa-11e9-9b3e-36dd9c3d024b.png">

1. It says 45 releases of borges in one day. Which doesn't look right
2. The legend is on the right, you need to scroll to it. It's different from all other our charts.

<img width="435" alt="Screenshot 2019-06-17 at 12 25 29" src="https://user-images.githubusercontent.com/406916/59597828-07966a80-90fb-11e9-877f-35b34ea36cbc.png">

1. It says 19 releases of lookout on Thu 28. Which month? Which year?

**Comment by gomesfernanda** [comment]
Covered by https://github.com/src-d/sourced-ui/pull/158

**Comment by smacker** [comment]
pr wasn't merged and can't be merged as it is

**Comment by smacker** [comment]
fixed by #160
