### ISSUE TITLE
Number and legend overlap each other

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#116]
<img width="469" alt="Screenshot 2019-06-17 at 12 26 20" src="https://user-images.githubusercontent.com/406916/59597875-239a0c00-90fb-11e9-86d1-6acad922d23a.png">

**Comment by carlosms** [comment]
Note: happens also in v0.2.0, before the redesign.

**Comment by smacker** [comment]
Apparently, it looks rather unfixable at the current state.
There are no properties that would allow to move legend or add any margin/padding.

The chart uses `legacy-chart-nvd3` plugin which is a tiny wrapper around [nvd3](https://github.com/novus/nvd3) library that isn't maintained anymore. So it looks like the problem is in the underlying library. 

There is an issue to [replace it with something else](https://github.com/apache/incubator-superset/issues/7352) but not much progress so far.

Taking into account very low priority of this issue I would just close it and hope it will be fixed soon by new chart plugins from upstream.

//cc @carlosms

**Comment by carlosms** [comment]
:+1: let's close, with the information you provide the reasonable thing to do is assume this is a very minor limitation on Superset.
