### ISSUE TITLE
Buttons looks incorrent

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#122]
After redesign:
<img width="236" alt="Screenshot 2019-06-17 at 12 45 41" src="https://user-images.githubusercontent.com/406916/59599066-f3a03800-90fd-11e9-88d9-500b5b1c0767.png">

Before:
<img width="224" alt="Screenshot 2019-06-17 at 12 46 59" src="https://user-images.githubusercontent.com/406916/59599103-04e94480-90fe-11e9-963c-2129bf238fee.png">

**Comment by dpordomingo** [comment]
After trying current `sourced v0.14.0-beta.5` with a custom `sourced-ui` docker image built from [`sourced-ui-branding`](https://github.com/src-d/sourced-ui/tree/sourced-ui-branding), I got:
![image](https://user-images.githubusercontent.com/2437584/59822899-7d354d00-932c-11e9-80a4-f01852fd946b.png)
I'd say that it addresses the described issues, so I'll try to rebase against current `master` and try again there.
