### ISSUE TITLE
Table headers look incorrect

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#123]
After redesign.

Before:
<img width="1144" alt="Screenshot 2019-06-17 at 12 47 51" src="https://user-images.githubusercontent.com/406916/59599200-3e21b480-90fe-11e9-9b3e-a2c52cc0cd38.png">

After:
<img width="1145" alt="Screenshot 2019-06-17 at 12 47 42" src="https://user-images.githubusercontent.com/406916/59599212-44b02c00-90fe-11e9-9da4-4ab55236bc57.png">

**Comment by dpordomingo** [comment]
After trying current `sourced v0.14.0-beta.5` with a custom `sourced-ui` docker image built from [`sourced-ui-branding`](https://github.com/src-d/sourced-ui/tree/sourced-ui-branding), I got:
![image](https://user-images.githubusercontent.com/2437584/59822990-d1d8c800-932c-11e9-9698-6d2cbfc48bf7.png)
I'd say that it addresses the described issues, so I'll try to rebase against current `master` and try again there.
