### ISSUE TITLE
Close button isn't clickable on sqllab params

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#124]
After redesign the "x" in popup doesn't react on anothing:

<img width="938" alt="Screenshot 2019-06-17 at 12 51 20" src="https://user-images.githubusercontent.com/406916/59599373-ac667700-90fe-11e9-9d9c-6e0b47c4f35f.png">

**Comment by smacker** [comment]
Same on UAST popup

**Comment by dpordomingo** [comment]
After trying `parameters` and `uast` popus over current `sourced v0.14.0-beta.5` with a custom `sourced-ui` docker image built from [`sourced-ui-branding`](https://github.com/src-d/sourced-ui/tree/sourced-ui-branding), I'd say that it addresses the described issues, so I'll try to rebase against current `master` and try again there.

<details>
<summary>Query to obtain `uast` popup:</summary>
<pre>
SELECT * FROM (
    SELECT cf.file_path,
           UAST(f.blob_content, LANGUAGE(f.file_path,  f.blob_content)) as uast
    FROM ref_commits r
    NATURAL JOIN commit_files cf
    NATURAL JOIN files f
    WHERE r.ref_name = 'HEAD'
    AND r.history_index = 0
) t WHERE uast != ''
LIMIT 2;
</pre>
</details>
