### ISSUE TITLE
Top menu looks incorrect

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#125]
After redesign.

Before:
<img width="339" alt="Screenshot 2019-06-17 at 12 54 02" src="https://user-images.githubusercontent.com/406916/59599528-1121d180-90ff-11e9-8547-e0c6596ef1bd.png">

After:
<img width="348" alt="Screenshot 2019-06-17 at 12 53 57" src="https://user-images.githubusercontent.com/406916/59599532-15e68580-90ff-11e9-8e27-7739512c4047.png">

**Comment by dpordomingo** [comment]
After trying current `sourced v0.14.0-beta.5` with a custom `sourced-ui` docker image built from [`sourced-ui-branding`](https://github.com/src-d/sourced-ui/tree/sourced-ui-branding), I got:
![image](https://user-images.githubusercontent.com/2437584/59822866-642c9c00-932c-11e9-81af-6d23a7393709.png)
I'd say that it addresses the described issues, so I'll try to rebase against current `master` and try again there.
