### ISSUE TITLE
Add dashboard for gitcollector and ghsync progress

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ui#133]
The goal is to have a dashboard that shows the current download progress for gitcollector and ghsync.
The progress will be taken from tables with total/done columns.

It will also need to have some introductory text that explains how data is being downloaded, how you can refresh the dashboard charts, how you can explore with partial results, etc. cc @src-d/product for this.

**Comment by carlosms** [comment]
Depends on https://github.com/src-d/ghsync/issues/31

**Comment by se7entyse7en** [comment]
I don't know about gitcollector, but I'm working on the ghsync part.

**Comment by smacker** [comment]
gitcollector creates `gitcollector_something` table with progress in `main` db. Most probably it makes sense to implement charts for both of them in the same PR.

**Comment by se7entyse7en** [comment]
> Most probably it makes sense to implement charts for both of them in the same PR.

It makes sense. BTW where these two charts should leave? /cc @marnovo

**Comment by smacker** [comment]
There is a default dashboard:
<img width="489" alt="Screenshot 2019-06-21 at 14 17 06" src="https://user-images.githubusercontent.com/406916/59921838-48f68500-942f-11e9-9deb-78a38700f72a.png">

we discussed before it should be displayed there. Just add the progress somewhere and product will re-organize the layout and provide new text later.

**Comment by carlosms** [comment]
Let's put the charts in the dashboard with the "placeholder" title.

By the way we have 2 dashboards with the title "Welcome". Could you please rename the one with gitbase data to something like... "Code" maybe? We can rename it later, but at least we don't have repeated names.

**Comment by se7entyse7en** [comment]
@smacker thanks!
