### ISSUE TITLE
Manual testing for typography branch

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#134]
1. Checkout to [`sourced-ui-branding`](https://github.com/src-d/sourced-ui/tree/sourced-ui-branding) branch
2. Rebase it on master if needed
3. Go through [issues related to branding/typography](https://github.com/src-d/sourced-ui/labels/typography), make sure they are fixed
4. Go through pages see that nothing new is broken
5. Create a PR from the branch (or commit if the branch contains non-typography commits already)

**Comment by dpordomingo** [comment]
About 
>_3. Go through open issues in this repo related to redesign, make sure they are fixed_

Is there any way to know which issues should be validated?
A list of issues would be welcomed for newcomers :nerd_face: 

/cc @ricardobaeta @smacker

**Comment by dpordomingo** [comment]
About
>_1. Checkout to typography branch_

which branch/commits contains the changes to be validated?
https://github.com/src-d/sourced-ui/branches/all

**Comment by dpordomingo** [comment]
About

>_3. Go through open issues in this repo related to redesign, make sure they are fixed_

@ricardobaeta sent me by slack:
- https://github.com/src-d/sourced-ui/issues/125
- https://github.com/src-d/sourced-ui/issues/124
- https://github.com/src-d/sourced-ui/issues/123
- https://github.com/src-d/sourced-ui/issues/122

Let me know if there's any other that I should consider

**Comment by smacker** [comment]
<img width="1037" alt="Screenshot 2019-06-19 at 18 04 18" src="https://user-images.githubusercontent.com/406916/59781747-bd5ce700-92bc-11e9-90a8-6db046e450b4.png">

<img width="1017" alt="Screenshot 2019-06-19 at 18 04 29" src="https://user-images.githubusercontent.com/406916/59781752-c0f06e00-92bc-11e9-854d-1c3c5242a326.png">

**Comment by dpordomingo** [comment]
commit containing typograpy: abb3431b
