### ISSUE TITLE
Charts legends are unreadable with repos from ghcollector

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#135]
<img width="1467" alt="Screenshot 2019-06-18 at 15 42 28" src="https://user-images.githubusercontent.com/406916/59689400-e5c2e380-91df-11e9-8d49-1a6b9a94c587.png">

<img width="1472" alt="Screenshot 2019-06-18 at 15 41 49" src="https://user-images.githubusercontent.com/406916/59689426-ece9f180-91df-11e9-930a-660bedf6ddf8.png">

**Comment by carlosms** [comment]
Was this fixed in #163?

**Comment by smacker** [comment]
yep. fixed
