### ISSUE TITLE
Make is tagging docker hub images with `latest` for beta releases

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ui#138]
Right now `latest`is `v0.3.0-beta.2`, which shouldn't happen. `latest` should point to `v0.2.0`. Maybe it's a bug introduced in #100.
https://hub.docker.com/r/srcd/sourced-ui/tags

**Comment by se7entyse7en** [comment]
It seems that we just need to add this condition in the `docker-push` target of the `Makefile` before tagging and pushing `latest`:

```if [ -n "$(DOCKER_PUSH_LATEST)" ];```

**Comment by smacker** [comment]
was fixed by #147
