### ISSUE TITLE
sqllab - really bad experience on non-chrome browser

### ISSUE THREAD

**Issue by kuba--** [src-d/sourced-ui#150]

**Comment by se7entyse7en** [comment]
I guess that we can't do that much here since we're relying on superset. We could work on this upstream to avoid having too many conflicts if we work on our fork. wdyt @smacker?

**Comment by se7entyse7en** [comment]
@kuba-- do you perhaps remember whether it was in terms of performance? UI/UX issues? or other stuffs?

**Comment by smacker** [comment]
there is no description of the issue and the title is way too broad.
It's not actionable in any way, we should just close it.

**Comment by kuba--** [comment]
Guys, lack of detailed description sucks (my bad). If you still have environment to test it out, I'll go through this again (mainly on safari).
But as far as i remember it was UI issue.

**Comment by smacker** [comment]
@kuba-- use dogfood instance https://instance-1.infra.dogfood.stg.srcd.host (you can contact Alex Corcoles if you have any problems with it)

**Comment by kuba--** [comment]
Thanks, so there are some issues with _SQLLab/SQLEditor_ on Safari.
<img width="510" alt="Screen Shot 2019-10-18 at 22 12 24" src="https://user-images.githubusercontent.com/4056521/67125569-6842ca80-f1f5-11e9-8e02-da9aab907ae2.png">
All of them are related to editing SQL. Sometimes cursor caret does not follow you (and it's couple characters behind  even if you appending text like in attachment). Sometimes you cannot delete a word after you move the cursor back. All kind of issues are related to editing (you have to play with non-chrome/safari browser).
For it looks like the embedded editor widget does not support safari.

**Comment by kuba--** [comment]
Btw. I tried to make a screenshot, but it does not contain a cursor caret ;(
