### ISSUE TITLE
proposal - UAST integrated with repos

### ISSUE THREAD

**Issue by kuba--** [src-d/sourced-ui#151]
It would be good if uast was integrated with rest of the stuff. So far it's kind of independent thingy with some `hello.java` examples. Moreover you cannot load source code from your running repos.

**Comment by smacker** [comment]
not sure what you mean by integration. When you use `UAST` function in SQL Lab we display UAST.

**Comment by kuba--** [comment]
I mean UAST tab (not functions). Can we somehow make this tab related to the repos. So I can pick a file from one of repos.

**Comment by dpordomingo** [comment]
Many things could be asked.
- how would be selected the file? An input to filter by repo and filename?
- which version of the file? Latest, or select by commit?
- could the user do: `select  * from repos`, then right click in a repo, and then open its tree, and choose a file from there to be opened in the uast tab?

**Comment by kuba--** [comment]
First baby step - super simple - instead of gist (whatever) open a local file, and it goes to the directory where your repos are

**Comment by kuba--** [comment]
... but `select files...` and click on the filename, choos `show uast`, would be perfect.

**Comment by dpordomingo** [comment]
When you say "open a local file", do you mean:
- upload a file from your PC, or
- browse a file from gitbase directory?

**Comment by kuba--** [comment]
I think it makes more sense to pick a file from gitbase's repo folder, so the second option.
