### ISSUE TITLE
Repository count on preset dashboard is rounded

### ISSUE THREAD

**Issue by smola** [src-d/sourced-ui#153]
- Repository count on preset dashboard is rounded to 10s.
- The backing data and query is actually correct.
- Can be fixed by going to chart options -> Number format -> remove the format by clicking the `x`.

**Comment by gomesfernanda** [comment]
Covered by https://github.com/src-d/sourced-ui/pull/158

**Comment by smacker** [comment]
pr wasn't merged and can't be merged as it is

**Comment by smacker** [comment]
fixed by #160
