### ISSUE TITLE
UAST tab uses steam logo

### ISSUE THREAD

**Issue by jfontan** [src-d/sourced-ui#154]
The logo is from the gaming company and shop steam. We should change it t something else that is not a company logo because of copyright or wrong association.

**Comment by ricardobaeta** [comment]
I’m on this.

**Comment by ricardobaeta** [comment]
@smacker @carlosms @dpordomingo the font awesome icon is declared by a class on `<i class="fa fa-fw fa-steam"></i>`. I can't target the i:before and override `content: "\f1b6";`.

Could you please update the markup and use `<i class="fas fa-tree"></i>`? 

Before:
![image](https://user-images.githubusercontent.com/1746146/59955175-ae269680-9480-11e9-91a6-8bd292fa3587.png)

After:
![image](https://user-images.githubusercontent.com/1746146/59955220-e3cb7f80-9480-11e9-974f-678423b2b069.png)

Alternative: We're able to add a class to the UAST tab `<li>` and I can apply any .svg that we want.

**Comment by ricardobaeta** [comment]
The first alternative solution can be found on [this PR](https://github.com/src-d/sourced-ui/pull/157).

**Comment by ricardobaeta** [comment]
Closing this per [objective accomplishment](https://github.com/src-d/sourced-ui/pull/157#event-2433740181).
