### ISSUE TITLE
Preset chart: "Number of commits per month breakdown per repo" legend taking too much space

### ISSUE THREAD

**Issue by smola** [src-d/sourced-ui#155]
- On medium-sized orgs (e.g. src-d, docker), the legend takes all space. It is possible to remove the legend, and the tooltip is still visible.
- So fat the tooltip works for me on Google Chrome, although it's not showing up in Firefox. I guess it's better that at least it shows up properly in Chrome?
- Also minor thing, the title should say "repository", not "repo", for consistency.

![2019-06-21-222335_2424x516_scrot](https://user-images.githubusercontent.com/23248/59949699-32265180-9474-11e9-8f3c-bbb3fb58424e.png)

**Comment by gomesfernanda** [comment]
Covered by https://github.com/src-d/sourced-ui/pull/158

**Comment by smacker** [comment]
pr wasn't merged and can't be merged as it is

**Comment by smacker** [comment]
fixed by #160
