### ISSUE TITLE
Default dashboard to open should be 'Welcome' instead of 'Overview'

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ui#156]
Tested on a local build after #148 was merged. 
`set_default_dashboard.py` is setting the first ID as the default. My dashboard ids are overview 1, collaboration 2, welcome 3.

**Comment by smacker** [comment]
In json welcome one [has id 2](https://github.com/src-d/sourced-ui/pull/148/files#diff-9efd28af90131b9d06e2da9f72a27017R7). And it imports with id 2 for me, so I can't reproduce.
An idea to try: replace `superset import_dashboards --recursive --path /home/superset/dashboards/metadata` with 2 commands first import welcome one then collaboration.

**Comment by se7entyse7en** [comment]
I have even different combination: 1 - Welcome, 2 - Collaboration, 3 - Overview.

<img width="384" alt="Screenshot 2019-06-24 at 12 03 26" src="https://user-images.githubusercontent.com/5599208/60010440-1ab7b600-9678-11e9-9311-056b2cfd3cac.png">

**Comment by smacker** [comment]
please try to replace `--recursive` import with a separate command for each dashboard as I described above. On my laptop I always have correct ids so I can't test it myself.
