### ISSUE TITLE
Beautify welcome dashboards

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#169]
Beautified version:

![image](https://user-images.githubusercontent.com/406916/60167265-0ce26c00-9803-11e9-8ad1-309a4914f13c.png)
![image (1)](https://user-images.githubusercontent.com/406916/60167275-110e8980-9803-11e9-9deb-965543050bc0.png)

Ricardo can provide full markdown for that.

**Comment by carlosms** [comment]
So is the markdown ready @ricardobaeta?

**Comment by ricardobaeta** [comment]
Is not yet approved by Marcelo. I'll reach out to you as soon as I have the final .md

**Comment by marnovo** [comment]
@carlosms @smacker @ricardobaeta please find the updated markdown files here for the welcome screens:

1. [Local Welcome screen dashboard markdown](https://gist.github.com/marnovo/87cc9b9b7c23e294cb397f401f48da95#file-sourced-ce-welcome-dualdash-local-md)
2. [Orgs Welcome screen dashboard markdown](https://gist.github.com/marnovo/87cc9b9b7c23e294cb397f401f48da95#file-sourced-ce-welcome-dualdash-orgs-md)

Notes:

- I have based these off the markdown shipped in the latest beta-8 release, so the correct links should be preserved.
- Besides the style, I made a few minor edits to the content based on feedback.
- The styles included shouldn't affect anything other than this dashboard.
- I have tested it thoroughly in different sizes and resolutions, and it didn't break.
- The _height_ of the dashboard element that contains this markdown must be adjusted given the narrower width. I'd give it some good extra margin room in the bottom just in case.

Sample screenshots:

<img width="1680" alt="Screen Shot 2019-06-26 at 2 02 29 PM" src="https://user-images.githubusercontent.com/15906764/60178166-1a0b5500-981b-11e9-8996-5c75a68991ed.png">
<img width="1680" alt="Screen Shot 2019-06-26 at 2 02 40 PM" src="https://user-images.githubusercontent.com/15906764/60178171-1d9edc00-981b-11e9-84e8-f45e05b266af.png">

**Comment by ricardobaeta** [comment]
It looks good, thanks for updating both markdown files.

**Comment by gomesfernanda** [comment]
LGTM, I'd just change the "Quick-start" to "Quickstart", so we comply with the guide itself (we should reach an agreement on how to write it, I believe Quickstart is the right one)
