### ISSUE TITLE
Broken links in welcome dashboards

### ISSUE THREAD

**Issue by dpordomingo** [src-d/sourced-ui#172]
- [x] http://127.0.0.1:8088/superset/dashboard/welcome  
&rarr; should be: http://127.0.0.1:8088/superset/welcome
- [x] https://docs.sourced.tech/community-edition/usage &rarr; fixed by https://github.com/src-d/sourced-ce/pull/107
- [x] https://docs.sourced.tech/community-edition/advanced &rarr; does no longer exist
- [x] https://sourced.tech/products/community-edition &rarr; not yet deployed https://github.com/src-d/landing/pull/417
- [x] https://sourced.tech/products/enterprise-edition &rarr; not yet deployed https://github.com/src-d/landing/pull/410

**Comment by warenlg** [comment]
+1

**Comment by EgorBu** [comment]
A bit of feedback from empathy session
https://github.com/src-d/empathy-sessions/issues/41
