### ISSUE TITLE
Figure out what is needed to make our charts support filtering

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ui#181]
Superset supports adding filters to the dashboards that can apply over all the other charts in real time.

This issue is to test if they work with our current gitbase and metadata dashboards, and document what changes are needed to make them work.

We may use this for things like https://github.com/src-d/sourced-ce/issues/109, https://github.com/src-d/sourced-ce/issues/113, or to filter data by time periods.

Related (maybe?): https://github.com/src-d/sourced-ui/issues/34

**Comment by smacker** [comment]
we used filters in demos. They just work.

**Comment by se7entyse7en** [comment]
Actually, I don't remember what problem I had when I opened #34. But as @smacker said filters work. Regarding #109 we could add a filter box to select `repo` type, but then this information should be available in all the underlying datasources of each chart.

**Comment by smacker** [comment]
should we just close it?

**Comment by carlosms** [comment]
In case it was not clear, my concern is not really if superset supports filtering, but if our dashboards support it.

I've done a quick test and it's not working out of the box. Maybe I did something wrong with the filter, I didn't spend any time trying to fix it.

As you can see in the images below, some charts apply the filter, some other break, and some other don't change.
Done with srcd/sourced-ui:v0.4.0-rc.2, `sourced init orgs bblfsh,golang-migrate`.

The dashboard json is here. exported from the UI: https://gist.github.com/carlosms/1bbbd3bae47488637542204cdbb40703


![a](https://user-images.githubusercontent.com/1469173/62233095-bc40ce80-b3bf-11e9-922c-bbc1abb75d08.png)
![b](https://user-images.githubusercontent.com/1469173/62233100-be0a9200-b3bf-11e9-8779-610c43034fe9.png)

**Comment by smacker** [comment]
To apply filters on charts there are 2 options:
1. Chart datasource should have a column with the same name as filter
2. Use jinja templates to generate sql (found it recently working on the demo)

Obviously, our current charts don't support filtering as the dashboards don't have any filters. If some of them do, it happened only by a chance.

This issue is about "figure out". There is no much to figure out. If you want to include any filters, charts must be updated to support that particular filter.

**Comment by carlosms** [comment]
Link to the filter method with jinja templates: https://help.pushmetrics.io/en/articles/2661887-how-to-pass-filter-parameters-from-a-dashboard-to-a-query
