### ISSUE TITLE
UAST tab changes some global styles.

### ISSUE THREAD

**Issue by dpordomingo** [src-d/sourced-ui#183]
_Originally posted by @carlosms in https://github.com/src-d/sourced-ui/pull/139#issuecomment-506668841_

I see the UAST tab changes some of the global styles. I have only noticed it in the top-right "New" button, it gets bigger. But there might be other places:

![a](https://user-images.githubusercontent.com/1469173/60332657-37613000-998f-11e9-8b09-51a4ba2e0844.png)

![b](https://user-images.githubusercontent.com/1469173/60332666-3d571100-998f-11e9-8314-c213e7d82b96.png)

**Comment by dpordomingo** [comment]
@ricardobaeta I think this issue would be solved by adding `, html` into [srcd/superset/assets/stylesheets/less/custom-brand.less#L128](https://github.com/dpordomingo/sourced-ui/blob/branding-typography/srcd/superset/assets/stylesheets/less/custom-brand.less#L128) as done in [srcd/superset/assets/src/uast/override.less#L5](https://github.com/dpordomingo/sourced-ui/blob/branding-typography/srcd/superset/assets/src/uast/override.less#L5)

**Comment by ricardobaeta** [comment]
Hi @dpordomingo ! This issue is now fixed as you can see 👇 . It will be included on the typography-fixes PR. Once it's merged we close this.

![image](https://user-images.githubusercontent.com/1746146/60664060-d8049380-9e58-11e9-8606-13b2b568ecf2.png)

**Comment by carlosms** [comment]
Fixed in #196
