### ISSUE TITLE
Extra outer scrollbar in SQL lab results

### ISSUE THREAD

**Issue by dpordomingo** [src-d/sourced-ui#184]
_Originally posted by @carlosms in https://github.com/src-d/sourced-ui/pull/139#issuecomment-506671899_

The SQL Lab results table has an extra outer scrollbar. 

![image](https://user-images.githubusercontent.com/2437584/60379552-469ab900-9a35-11e9-9ba2-effcd641cde6.png)

**Comment by ricardobaeta** [comment]
Hi @dpordomingo ! This issue is now fixed as you can see 👇 . It will be included on the typography-fixes PR. Once it's merged we close this.
