### ISSUE TITLE
Buttons does not keep size on action

### ISSUE THREAD

**Issue by dpordomingo** [src-d/sourced-ui#185]
_Originally posted by @carlosms in https://github.com/src-d/sourced-ui/pull/139#issuecomment-506673208_

I've found a missing change in button height. In this case it's a minor thing, but it means there might be other places where buttons are not consistent.

Before:
![Peek 2019-06-28 10-39](https://user-images.githubusercontent.com/1469173/60333539-3a5d2000-9991-11e9-8045-d18dc454434b.gif)

After:
![Peek 2019-06-28 10-38](https://user-images.githubusercontent.com/1469173/60333548-3df0a700-9991-11e9-8f13-dc089a9b4ee1.gif)

**Comment by dpordomingo** [comment]
I think that button size (width:height) should not change on active state.

**Comment by ricardobaeta** [comment]
Yes @dpordomingo I agree with you on this. It's already fixed as you can see 👇. It will be included on the typography-issues PR. Once merged we can close this.

![run-query-stop](https://user-images.githubusercontent.com/1746146/60600444-0e360a80-9da8-11e9-8697-e0db9f4d36a5.gif)

**Comment by carlosms** [comment]
Fixed in #196
