### ISSUE TITLE
UAST buttons in result tables has no margins

### ISSUE THREAD

**Issue by dpordomingo** [src-d/sourced-ui#186]
_Originally posted by @carlosms in https://github.com/src-d/sourced-ui/pull/139#issuecomment-506749695_

The UAST button inside the results table now overlaps one row with the next one so does not look as neat.

![image](https://user-images.githubusercontent.com/2437584/60379587-e5271a00-9a35-11e9-880b-68c4a9c9dba6.png)

**Comment by ricardobaeta** [comment]
@dpordomingo This issue is already fixed as you can see 👇 . It will be included on the typography-fixes PR. We can close this when it's merged.

![image](https://user-images.githubusercontent.com/1746146/60603477-be5a4200-9dad-11e9-8f65-2c287c0dfe50.png)

**Comment by carlosms** [comment]
Fixed in #196
