### ISSUE TITLE
[SQL Lab] Proposal: add a close button to each query tab

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/sourced-ui#215]
In SQL Lab tab you need two clicks to close a query tab, and if you want to close many of them it's annoying. Most of the times I need to close many tabs when I'm actually interested in a single one, so I just click on `Close all other tabs`, but IMHO having a close button near the dropdown of each tab could be useful.

**Comment by carlosms** [comment]
The gray/green/red status circle to the left of the tab title is also the close button, if you hover you'll see the `x`.

Is that what you are describing, or something else?

**Comment by se7entyse7en** [comment]
😲 oh yes! I never noticed it!
