### ISSUE TITLE
Status table for gitcollector doesn't explain why missing repos

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/sourced-ui#228]
Currently, from the status table of gitcollector, it's not clear about the reason why `discovered != downloaded`. In this case `discovered = 10`, but `downloaded = 9`. From the logs, it seems that downloading for the `mloncode/ggnn_graph_classification` started, but never finished, and no error appears in the logs.

![Screenshot 2019-07-30 at 17 05 06](https://user-images.githubusercontent.com/5599208/62141871-93500900-b2ed-11e9-8190-1f302434847f.png)

Here are the logs:

![Screenshot 2019-07-30 at 17 14 53](https://user-images.githubusercontent.com/5599208/62141889-9ba84400-b2ed-11e9-9bfc-fd30d914ccc6.png)

**Comment by se7entyse7en** [comment]
\cc @jfontan @mcarmonaa

**Comment by dpordomingo** [comment]
Did not finish `mloncode/ggnn_graph_classification` considering the logs?
I see it as `finished` almost at the bottom of the screenshot, isn't it?

**Comment by mcarmonaa** [comment]
From the logs you can see how the repository you mentioned started and finished, and the final metrics the logs shows also seem correct `discover=10 download=10`, so maybe the problem it's from ui side not updating the data. Can you see if the table `gitcollector_metrics` in the db is correct?

**Comment by se7entyse7en** [comment]
You're right @dpordomingo! I completely missed that final logging, sorry for the noise then! Closing.
