### ISSUE TITLE
Update current dashboards & queries for gitbase-spark-connector

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ui#235]
Replicate (and adapt when necessary) queries and dashboards from the current CE dashboards for EE.

If the queries are not compatible, we will need to have different json files for CE and EE. They should be loaded automatically on bootstrap, just like we do for CE.
We need to pay attention also to the internal links from the welcome dashboard to the other ones.

note: we already have an undocumented env var, `MODE=Community/Enterprise`, used in `superset_config.py` for the database connection string.

**Comment by carlosms** [comment]
With the new CE & EE roadmap, there is no need to keep both versions. The current dashboards need to be updated to work with gitbase-spark-connector.

For now we need to start working on it, to find incompatibilities and possible bugs in gitbase-spark-connector as soon as possible.
To help with development, let's work with PRs against a new branch, `gsc`. This way we can have smaller PRs before merging everything to master.

**Comment by carlosms** [comment]
Adding the 'blocked' label because we should wait for #251 to be merged first.

**Comment by se7entyse7en** [comment]
Removing the `blocked` label as #251 has been merged.

**Comment by se7entyse7en** [comment]
As discussed in Apps sync of 2019-10-02 this is a `won't do`.
