### ISSUE TITLE
Support SQL Lab table previews with gitbase-spark-collector

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ui#245]

**Comment by smacker** [comment]
I'm not sure this issue should be in ui repo.
Preview for tables registered in spark work just fine. Views don't. (you can validate it on our demo instance)
Also there is a issue in gsc: https://github.com/src-d/gitbase-spark-connector-enterprise/issues/110
And dp team recomends to apply the fix to pyhive.

**Comment by se7entyse7en** [comment]
Sorry, I opened #246 after seeing this. BTW the fix in pyhive doesn't work: that part of the code is not being used when the query for the preview is requested by the UI.

**Comment by se7entyse7en** [comment]
The query is built by the [`select_star`](9ef3dd2102f04bcceR1424) method that is then passed to the FE [here](https://github.com/src-d/sourced-ui/blob/master/superset/superset/assets/src/SqlLab/actions/sqlLab.js#L288).
