### ISSUE TITLE
source{d} color scheme by default on Charts Visual Properties

### ISSUE THREAD

**Issue by ricardobaeta** [src-d/sourced-ui#255]
## Context 

This issue is related to the [source{d}-branded superset UI EPIC](https://github.com/src-d/backlog/issues/1427), on what concerns the **source{d} color scheme by default on chart visual properties** Story.

It inherits the same rationale: *As a Product, Marketing or sales team member I want product users to have a branded interface so that I can reinforce the source{d} brand in their minds and provide them a coherent end-to-end experience.*

This issue didn't birth here, but rather with a [very fancy PR](https://github.com/src-d/sourced-ui/pull/241) made by @dpordomingo, that couldn't have streamlined more the accomplishment of this objective.

## Requirements

- Apply our brand guidelines, mainly regarding colour usage and get the most out of Tints & Shades.
- Discuss/Propose/Justify/Agree on the design decisions made in the [source{d} Branded UI design doc](https://docs.google.com/document/d/1cD7SvX1MDrUxBsxjb7AYAxQUSCdhxGWrktrQKlPVPyw/edit).
- Test David's PR more times (as color change)
- Test David's PR for color blindness/impairments
- Test David's PR color pairs/triples (colors "close" to each other in the palette)
- Team up with Anita Lillie (Superset Design Community) as she is, in fact, a Data Visualization Designer above all, and she is excited to jump on board.
- Deliver as a PR

## Current status

![image](https://user-images.githubusercontent.com/1746146/63039106-7fde9980-beba-11e9-89e5-a606d6aae230.png)

## Related

- [P CC & EE Action Plan](https://docs.google.com/document/d/11t6egk7vewRwAzm9HqzntAh7rT3jENiZrMoj9nOxLgE/edit#heading=h.qhzm4nnshexd)

**Comment by dpordomingo** [comment]
Is this issue going to be closed by the following issues?
- [ ] Use reduced palettes #258
- [ ] Apply our brand colors on source{d} dashboards #259

Or is it going to be needed any other work @ricardobaeta ?

**Comment by ricardobaeta** [comment]
@dpordomingo Yes, it's going to be closed to #258 and #259

**Comment by ricardobaeta** [comment]
@dpordomingo both #258 and #259 are merged. Closing this per objective accomplishment. Thank you!
