### ISSUE TITLE
Update superset to 0.34.0

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ui#276]
New stable release: https://github.com/apache/incubator-superset/releases/tag/0.34.0

**Comment by smacker** [comment]
No need to update to 0.34.0. It has absolutely the same code as rc1 which we are using right now but with updated changelog / some minor license updates.

**Comment by carlosms** [comment]
Since we are low on tasks, this could be a good chance for someone other than @smacker to get familiar with the process described in https://github.com/src-d/sourced-ui/blob/master/CONTRIBUTING.md#merging-upstream (BTW good job describing the steps @smacker)

**Comment by smacker** [comment]
rc1 was cut from master which makes it simplier to merge future releases. 0.34.0 was cut from release branch.

**Comment by dpordomingo** [comment]
As discussed during the last TFM, we'll wait till the next oficial release, because this one does not add much value compared with the current `0.34.0rc1`
