### ISSUE TITLE
When running with https favorite status is still requested with http

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/sourced-ui#278]
For a demo environment running with https, when opening a dashboard the request for favorite status is done on http causing an error, and shows banner `'There was an issue fetching the favorite status of this dashboard.'`

**Comment by se7entyse7en** [comment]
For demos this has been _fixed_ by removing the [`catch` of the error](https://github.com/src-d/sourced-ui/blob/master/superset/superset/assets/src/dashboard/actions/dashboardState.js#L72).

**Comment by smacker** [comment]
The proper fix is included in v0.34.1: https://github.com/apache/incubator-superset/pull/8013
We can backport it or just wait a bit.

**Comment by se7entyse7en** [comment]
Great that has been fixed upstream 👍

**Comment by se7entyse7en** [comment]
I'd backport it as it is a very isolated thing and also would remove us a step when setting up demos.

**Comment by smacker** [comment]
There are enough votes for releasing 0.34.1rc2 as 0.34.1 already from Superset team.
72 hours voting process by Apache Incubator started 2 days ago.
https://lists.apache.org/thread.html/e60f080ebdda26896214f7d3d5be1ccadfab95d48fbe813252762879@%3Cdev.superset.apache.org%3E

it makes sense to wait and update srcd-ui to 0.34.1.

**Comment by se7entyse7en** [comment]
Thanks for the link! Yes then, let's wait 👍

**Comment by smacker** [comment]
released: https://github.com/apache/incubator-superset/releases/tag/0.34.1
