### ISSUE TITLE
Allow changing order of tabs in dashboards

### ISSUE THREAD

**Issue by smola** [src-d/sourced-ui#60]
Allow changing order of tabs in dashboards

This was added 20 days ago to Superset master:
- https://github.com/apache/incubator-superset/pull/7390
- https://github.com/apache/incubator-superset/commit/9e703f399b78af1a198ba5d69353385b77dd701e

I'm not sure whether it made it into any release yet (0.33.0rc1)?

Opening the issue here just to track ourselves.

**Comment by smacker** [comment]
It's not in 0.33.

**Comment by zurk** [comment]
Workaround:
1. Open Dashboard.
2. Press `Edit dashboard`.
3. Press  `Edit dashboard metadata`. (press an arrow close to `Switch to view mode` to see this button)
4. Go to `Position JSON` field. 
5. Find `"type":"TABS"` (in the end of the JSON in my case) and change the order of the `"children"`  on the same level.

Example:
```JSON
{

"...": {"..."},

"TABS-y3H9K9tIPM":
    {"children":["TAB-6pFKAgBaT","TAB-jKeAvr9fJ","TAB--aWoyKHn5","TAB-2DqtP-p_8","TAB-kb1aHKZWeK"],
    "id":"TABS-y3H9K9tIPM","meta":{},"type":"TABS"}}
}
```
If we want to change 1st and 2nd tabe we should change 1st and 2nd strings in children field: 
```JSON
{

"...": {"..."},

"TABS-y3H9K9tIPM":
    {"children":["TAB-jKeAvr9fJ","TAB-6pFKAgBaT","TAB--aWoyKHn5","TAB-2DqtP-p_8","TAB-kb1aHKZWeK"],
    "id":"TABS-y3H9K9tIPM","meta":{},"type":"TABS"}}
}
```

6. Press `Save` button.
