### ISSUE TITLE
Allow to configure gitbase spark connector via environmental variables

### ISSUE THREAD

**Issue by rporres** [src-d/sourced-ui#77]
I need to be able choose between gitbase or gitbase spark connector via configuration variables rather than adding a datasource from superset. That also means that gitbase configuration via env variables should not be mandatory or at least check if either gitbase or gitbase spark connector configuration is present.

**Comment by smacker** [comment]
taking into account that we will use spark-connector only for EE and gitbase only for CE, I would propose:
1. new env variable `MODE: Community|Enterprise`
2. depends on it we will use different prefixes for datasource mysql/hive but the same current variables to build the connection string: GITBASE_HOST/PORT/...
3. later we can use the same variable to load different dashboards and do whatever other changes we need.

**Comment by smacker** [comment]
Env var is merged in master.
But our superset can't work with spark yet because it requires patched PyHive so I keep the issue open for now.
We have a PR in our PyHive fork but it's not merged yet: https://github.com/src-d/PyHive/pull/1

**Comment by smacker** [comment]
fixed by https://github.com/src-d/sourced-ui/pull/87
