### ISSUE TITLE
Publish Docker image

### ISSUE THREAD

**Issue by smola** [src-d/sourced-ui#84]

**Comment by carlosms** [comment]
Done:
https://github.com/src-d/sourced-ui/releases/tag/v0.1.0
https://hub.docker.com/r/srcd/sourced-ui/tags

@smola before the rename we published the `srcd/superset` image. Do we want to remove it from docker hub to avoid confusion, or is it ok to just leave it?
https://hub.docker.com/r/srcd/superset/tags

**Comment by carlosms** [comment]
Done, old image removed from dockerhub.
