### ISSUE TITLE
Update to superset release 0.33

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ui#89]
Instruction is here: https://github.com/src-d/sourced-ui/issues/78
Then need manual testing (if I remember right css changed a bit. need amends to uast tab and maybe to popup in gitlab as well)

**Comment by carlosms** [comment]
One thing to take into account is the DB upgrade.
Right now we skip `docker-init.sh` completely if the DB contains the admin user, but it also includes `superset db upgrade`
https://github.com/src-d/sourced-ui/blob/master/superset/contrib/docker/docker-entrypoint.sh#L20

**Comment by carlosms** [comment]
Reopening to update the version in the README, and add it to the changelog.

**Comment by carlosms** [comment]
Maybe for the readme let's just say it's based on superset, removing the exact version. And then in the release notes we will notify when we merge a new version, that should be enough.

**Comment by smacker** [comment]
looks like it was done in https://github.com/src-d/sourced-ui/pull/101
