### ISSUE TITLE
Gitbase datasource is not updated if we restart sourced-ui with a changed GITBASE_* env variable

### ISSUE THREAD

**Issue by rporres** [src-d/sourced-ui#96]
This makes impossible to reconfigure via a restart with env variable changed if something like GITBASE_PASSWORD has changed

**Comment by smacker** [comment]
It's a little tricky from the distributed deployment point of view.
The datasource is saved in DB.
So most probably it should be updated only in DB migration job and should be disable when [SUPERSET_NO_DB_INIT](https://github.com/src-d/sourced-ui/pull/99) is passed. Is that correct?

**Comment by meyskens** [comment]
Yup, we will run `docker-init.sh` on every update so you can safely place it in there
